variables:
  AUTO_CNB_RUN_IMAGE: harbor.dcas.dev/docker.io/paketobuildpacks/run:tiny-cnb
  BUILD_KANIKO_DISABLED: "true"
  DEPLOY_DISABLED: "true"

autobuild golang:
  tags: []

include:
  - remote: 'https://gitlab.dcas.dev/open-source/gitlab-ci-templates/-/raw/master/auto/Auto-GoMod.gitlab-ci.yml'
